"""SQLite Persistent Storage, Async/Background Memory Consolidation, & Markdown RAG Knowledge Base."""

import asyncio
import os
import re
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from assessor.telemetry import log_structured_event, trace_span

DEFAULT_DB_PATH = os.environ.get("SQLITE_DB_PATH", "assessments.db")
DEFAULT_GUIDELINES_PATH = str(
    Path(__file__).resolve().parent.parent / "sample_data" / "architecture_guidelines.md"
)

# Background memory cache for asynchronous consolidation off the critical path
_CONSOLIDATED_MEMORY_CACHE: Dict[str, List[Dict[str, str]]] = {}


class ContextCompactor:
    """Short-term memory manager that compresses and consolidates multi-turn context via async and background tasks."""

    @staticmethod
    @trace_span(name="memory.compact_context", component="memory")
    def compact_history(
        messages: List[Dict[str, str]], max_chars: int = 6000
    ) -> List[Dict[str, str]]:
        """Compacts conversation history while preserving system prompts, latest turn, and key decisions."""
        total_chars = sum(len(m.get("content", "")) for m in messages)
        if total_chars <= max_chars or len(messages) <= 2:
            return messages

        compacted: List[Dict[str, str]] = []
        # Always keep the first message if it is system/context
        if messages and messages[0].get("role") in ("system", "user"):
            compacted.append(messages[0])

        # Summarize middle turns into a concise architectural state digest
        middle_turns = messages[1:-1]
        summary_bullets = []
        for turn in middle_turns:
            content = turn.get("content", "")
            # Extract lines mentioning scores, gates, or decisions
            key_lines = [
                line.strip()
                for line in content.splitlines()
                if any(
                    k in line.lower()
                    for k in ("gate", "score", "status", "approved", "review", "iam", "adk")
                )
            ]
            if key_lines:
                summary_bullets.append(" | ".join(key_lines[:3]))
            elif content:
                summary_bullets.append(content[:150].strip() + "...")

        digest_text = (
            "[COMPACTED CONTEXT DIGEST — Prior Turns Summarized]\n"
            + "\n".join(f"- {b}" for b in summary_bullets[-5:])
        )
        compacted.append({"role": "system", "content": digest_text})

        # Always preserve the most recent message
        compacted.append(messages[-1])

        log_structured_event(
            event_type="memory.context_compacted",
            payload={
                "original_turns": len(messages),
                "compacted_turns": len(compacted),
                "original_chars": total_chars,
                "new_chars": sum(len(m.get("content", "")) for m in compacted),
            },
            severity="INFO",
            component="memory",
        )
        return compacted

    @classmethod
    @trace_span(name="memory.compact_context_async", component="memory")
    async def compact_history_async(
        cls, messages: List[Dict[str, str]], max_chars: int = 6000
    ) -> List[Dict[str, str]]:
        """Executes history compaction asynchronously in a background thread (non-blocking)."""
        return await asyncio.to_thread(cls.compact_history, messages, max_chars)

    @classmethod
    def generate_and_consolidate_memory_background(
        cls, session_id: str, messages: List[Dict[str, str]], max_chars: int = 6000
    ) -> asyncio.Task:
        """Executes memory generation and consolidation asynchronously as a background task (asyncio.create_task)."""

        async def _background_consolidation_worker() -> List[Dict[str, str]]:
            compacted = await cls.compact_history_async(messages, max_chars=max_chars)
            _CONSOLIDATED_MEMORY_CACHE[session_id] = compacted
            log_structured_event(
                event_type="memory.background_consolidation.completed",
                payload={
                    "session_id": session_id,
                    "consolidated_turns": len(compacted),
                    "mode": "background_async_task",
                },
                severity="INFO",
                component="memory",
            )
            return compacted

        return asyncio.create_task(_background_consolidation_worker())

    @classmethod
    def get_consolidated_memory(cls, session_id: str) -> Optional[List[Dict[str, str]]]:
        """Retrieves consolidated session history generated by the background worker."""
        return _CONSOLIDATED_MEMORY_CACHE.get(session_id)


class GuidelinesRAG:
    """Lightweight Markdown chunking & keyword/category RAG engine for Enterprise Architecture Guidelines."""

    CATEGORY_MAP = {
        "security": "gate-1-security--governance",
        "governance": "gate-1-security--governance",
        "architecture": "gate-2-architecture--scalability",
        "scalability": "gate-2-architecture--scalability",
        "cost": "gate-3-tokenomics--cost-efficiency",
        "tokenomics": "gate-3-tokenomics--cost-efficiency",
        "eval": "gate-4-observability--eval-readiness",
        "observability": "gate-4-observability--eval-readiness",
    }

    def __init__(self, guidelines_path: Optional[str] = None) -> None:
        self.guidelines_path = guidelines_path or DEFAULT_GUIDELINES_PATH
        self.chunks: List[Dict[str, Any]] = self._load_and_chunk()

    def _load_and_chunk(self) -> List[Dict[str, Any]]:
        path = Path(self.guidelines_path)
        if not path.exists():
            return []

        raw_text = path.read_text(encoding="utf-8")
        sections = re.split(r"\n(?=## Gate \d+:)", raw_text)
        chunks: List[Dict[str, Any]] = []

        for sec in sections:
            if not sec.strip().startswith("## Gate"):
                continue
            lines = sec.strip().splitlines()
            header = lines[0].replace("## ", "").strip()
            # Extract explicit anchor if present or generate slug
            anchor_match = re.search(r"<!--\s*Anchor:\s*(#[a-z0-9\-]+)\s*-->", sec)
            if anchor_match:
                anchor = anchor_match.group(1)
            else:
                slug = re.sub(r"[^a-z0-9]+", "-", header.lower()).strip("-")
                anchor = f"#{slug}"

            category = "general"
            if "Gate 1" in header:
                category = "security"
            elif "Gate 2" in header:
                category = "architecture"
            elif "Gate 3" in header:
                category = "cost"
            elif "Gate 4" in header:
                category = "eval"

            chunks.append(
                {
                    "section_title": header,
                    "category": category,
                    "anchor": anchor,
                    "citation_url": f"sample_data/architecture_guidelines.md{anchor}",
                    "content": sec.strip(),
                }
            )
        return chunks

    @trace_span(name="memory.rag_search", component="rag")
    def search(self, query: str, category: str = "all", top_k: int = 2) -> List[Dict[str, Any]]:
        """Retrieves relevant architecture guideline sections with exact citation anchors."""
        if not self.chunks:
            self.chunks = self._load_and_chunk()

        cat_norm = (category or "all").lower().strip()
        query_terms = [
            t.lower()
            for t in re.findall(r"[a-zA-Z0-9_\-]+", query or "")
            if len(t) > 2
        ]

        scored_chunks: List[Dict[str, Any]] = []
        for chunk in self.chunks:
            score = 0.0
            content_lower = chunk["content"].lower()

            # Category match boost
            if cat_norm != "all":
                if chunk["category"] == cat_norm or self.CATEGORY_MAP.get(cat_norm, "") in chunk["anchor"]:
                    score += 15.0

            # Keyword overlap score
            for term in query_terms:
                occurrences = content_lower.count(term)
                if occurrences > 0:
                    score += 3.0 * min(occurrences, 4)

            # Default baseline score so all gates can be inspected if query is generic
            if score == 0.0 and cat_norm == "all":
                score = 1.0

            if score > 0:
                scored_chunks.append({**chunk, "relevance_score": round(score, 2)})

        scored_chunks.sort(key=lambda x: x["relevance_score"], reverse=True)
        results = scored_chunks[:top_k]

        log_structured_event(
            event_type="rag.guidelines_retrieved",
            payload={
                "query": query,
                "category": category,
                "matched_count": len(results),
                "citations": [r["citation_url"] for r in results],
            },
            severity="INFO",
            component="rag",
        )
        return results


class AssessmentMemoryStore:
    """SQLite-backed persistent storage for customer engagement readiness assessments."""

    def __init__(self, db_path: Optional[str] = None) -> None:
        self.db_path = db_path or DEFAULT_DB_PATH
        self._init_db()

    def _get_conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self) -> None:
        with self._get_conn() as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS assessment_records (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    project_name TEXT NOT NULL,
                    customer_name TEXT DEFAULT 'Enterprise Customer',
                    total_score INTEGER NOT NULL,
                    security_score INTEGER DEFAULT 0,
                    architecture_score INTEGER DEFAULT 0,
                    cost_score INTEGER DEFAULT 0,
                    eval_score INTEGER DEFAULT 0,
                    readiness_status TEXT NOT NULL,
                    summary TEXT NOT NULL,
                    human_approved INTEGER DEFAULT 0,
                    reviewer_email TEXT DEFAULT NULL,
                    override_justification TEXT DEFAULT NULL,
                    created_at TEXT NOT NULL
                )
                """
            )
            conn.commit()

    @trace_span(name="memory.save_assessment", component="memory")
    def save_assessment(
        self,
        project_name: str,
        total_score: int,
        readiness_status: str,
        summary: str,
        security_score: int = 0,
        architecture_score: int = 0,
        cost_score: int = 0,
        eval_score: int = 0,
        customer_name: str = "Enterprise Customer",
    ) -> Dict[str, Any]:
        """Inserts a new assessment record into SQLite long-term memory."""
        created_at = datetime.now(timezone.utc).isoformat()
        with self._get_conn() as conn:
            cursor = conn.execute(
                """
                INSERT INTO assessment_records (
                    project_name, customer_name, total_score,
                    security_score, architecture_score, cost_score, eval_score,
                    readiness_status, summary, human_approved, created_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?)
                """,
                (
                    project_name,
                    customer_name,
                    int(total_score),
                    int(security_score),
                    int(architecture_score),
                    int(cost_score),
                    int(eval_score),
                    readiness_status,
                    summary,
                    created_at,
                ),
            )
            record_id = cursor.lastrowid
            conn.commit()

        record = self.get_assessment(record_id)
        log_structured_event(
            event_type="memory.record_saved",
            payload={
                "record_id": record_id,
                "project_name": project_name,
                "total_score": total_score,
                "readiness_status": readiness_status,
            },
            severity="INFO",
            component="memory",
        )
        return record or {}

    async def save_assessment_async(
        self,
        project_name: str,
        total_score: int,
        readiness_status: str,
        summary: str,
        security_score: int = 0,
        architecture_score: int = 0,
        cost_score: int = 0,
        eval_score: int = 0,
        customer_name: str = "Enterprise Customer",
    ) -> Dict[str, Any]:
        """Asynchronously persists an assessment record to SQLite via worker thread (non-blocking)."""
        return await asyncio.to_thread(
            self.save_assessment,
            project_name,
            total_score,
            readiness_status,
            summary,
            security_score,
            architecture_score,
            cost_score,
            eval_score,
            customer_name,
        )

    def schedule_background_save(
        self,
        project_name: str,
        total_score: int,
        readiness_status: str,
        summary: str,
        security_score: int = 0,
        architecture_score: int = 0,
        cost_score: int = 0,
        eval_score: int = 0,
        customer_name: str = "Enterprise Customer",
    ) -> asyncio.Task:
        """Schedules SQLite persistence as an asynchronous background task (asyncio.create_task)."""
        return asyncio.create_task(
            self.save_assessment_async(
                project_name=project_name,
                total_score=total_score,
                readiness_status=readiness_status,
                summary=summary,
                security_score=security_score,
                architecture_score=architecture_score,
                cost_score=cost_score,
                eval_score=eval_score,
                customer_name=customer_name,
            )
        )

    @trace_span(name="memory.get_assessment", component="memory")
    def get_assessment(self, record_id: int) -> Optional[Dict[str, Any]]:
        """Fetches a single assessment record by primary key ID."""
        with self._get_conn() as conn:
            row = conn.execute(
                "SELECT * FROM assessment_records WHERE id = ?", (int(record_id),)
            ).fetchone()
            return dict(row) if row else None

    @trace_span(name="memory.list_assessments", component="memory")
    def list_assessments(self, limit: int = 50) -> List[Dict[str, Any]]:
        """Lists historical assessment records ordered by newest first."""
        with self._get_conn() as conn:
            rows = conn.execute(
                "SELECT * FROM assessment_records ORDER BY id DESC LIMIT ?",
                (int(limit),),
            ).fetchall()
            return [dict(r) for r in rows]

    @trace_span(name="memory.approve_assessment", component="memory")
    def approve_assessment(
        self, record_id: int, reviewer_email: str, justification: str
    ) -> Dict[str, Any]:
        """Updates a PENDING_HUMAN_REVIEW record to APPROVED_WITH_CONDITIONS via HITL override."""
        existing = self.get_assessment(record_id)
        if not existing:
            raise ValueError(f"Assessment record ID {record_id} not found.")

        with self._get_conn() as conn:
            conn.execute(
                """
                UPDATE assessment_records
                SET readiness_status = 'APPROVED_WITH_CONDITIONS',
                    human_approved = 1,
                    reviewer_email = ?,
                    override_justification = ?
                WHERE id = ?
                """,
                (reviewer_email, justification, int(record_id)),
            )
            conn.commit()

        updated = self.get_assessment(record_id)
        return updated or {}
